server:
  port: 8022
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
